image:
  file: .gitpod.Dockerfile

tasks:
  - before: gdown --id 1IyIT2hAYcTlayuqc2l4Xd-4fDs2UxKpI && unzip database.zip -d server/exercises/sql/
    init: cd server && npm i
    command: npm run dev
  - init: cd frontend && npm i
    command: npm run serve
  